backend:
  name: git-gateway
  branch: main # Adjust to "master" if your Git repository uses it

media_folder: "public" # Folder where uploaded images/media will be stored
public_folder: "/" # Public path for media

collections:
  - name: "blog" # Identifier for this collection
    label: "Blog" # Visible name in the CMS
    folder: "src/content/blog" # Path to your blog folder
    create: true # Allow creating new entries
    slug: "{{slug}}" # Generate a unique slug for each entry
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Image", name: "image", widget: "image", required: false }
